kind: Pod
apiVersion: v1
metadata:
  name: kuard
spec:
  containers:
  - name: kurad
    image: gcr.io/kuar-demo/kuard-amd64:1
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
