apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: secret-test
  name: secret-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: secret-test
    spec:
      containers:
        - name: http-debug-server
          image: cotoami/http-debug-server:latest
          ports:
            - containerPort: 3000
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test-secret
                  key: password
